package com.dlfc.services.collect.entity;


import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class SysInfoAtt {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.ID
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.PINDEX
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.FILE_TYPE
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Integer fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.FILE_NAME
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.FILE_PATH
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.LID
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private String lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.FILE_REAL_NAME
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private String fileRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.CREATE_USER
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.CREATE_USER_IDENTITY
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.CREATE_TIME
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.MODIFY_USER
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.MODIFY_TIME
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.DELETE_FLG
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.VERSION
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info_att.SORT
     *
     * @mbggenerated Mon May 29 15:56:15 CST 2017
     */
    private Integer sort;
}
