package com.dlfc.services.collect.entity;




import java.util.Date;


@lombok.Getter
@lombok.Setter
public class UsrHouCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.ID
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.PINDEX
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.UID
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.HID
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private String hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.CTIME
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.CREATE_USER
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.CREATE_USER_IDENTITY
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.CREATE_TIME
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.MODIFY_USER
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.MODIFY_TIME
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.DELETE_FLG
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_hou_collection.VERSION
     *
     * @mbggenerated Tue May 30 08:57:29 CST 2017
     */
    private Integer version;

}