server:
  port: 28098

spring:
  application:
    name: dlfc-zfw-order-services

eureka:
  client:
    service-url:
      defaultZone: http://10.32.156.49:11111/eureka, http://10.32.156.49:11112/eureka