package com.dlfc.zfw.wechat.registry.entity;


import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class SysMobileCapcha {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.ID
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.PINDEX
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.MOBILE
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.SESSION_ID
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.TEMPLATE_ID
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.DOMAIN
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.DEVICE_ID
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.IP
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.VER_CODE
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private String verCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_mobile_capcha.CREATE_TIME
     *
     * @mbggenerated Fri Mar 31 10:54:56 CST 2017
     */
    private Date createTime;
}