package com.dlfc.zfw.wechat.registry.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class UsrUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.ID
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.PER_ID
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.AGT_CERT
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String agtCert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.MOBILE
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.EMAIL
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.PASSWORD
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.PAY_PWD
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String payPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.USERNAME
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.PRO_QUESTION
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String proQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.PRO_ANSWER
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String proAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.SECURITY_LEVEL
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short securityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.DISABLE_FLG
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short disableFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.LOGIN_IP
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.LAST_LOGIN_TIME
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.PASSWORD_LEVEL
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short passwordLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.CREATE_USER
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.CREATE_USER_IDENTITY
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.CREATE_TIME
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.MODIFY_USER
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.MODIFY_TIME
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.DELETE_FLG
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.VERSION
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.USERNAME_FLAG
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short usernameFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.USER_IDENTITY
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short userIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.ORIGIN
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.MARRIAGE
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.DEGREE
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.WORK_EXP
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short workExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.INDUSTRY
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.SALARY
     *
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    private Short salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.ID
     *
     * @return the value of usr_user.ID
     * @mbggenerated Tue May 30 08:58:10 CST 2017
     */
    public String getId() {
        return id;
    }
}