server:
  port: 28091

spring:
  application:
    name: dlfc-zfw-search-services

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:11112/eureka,http://eureka-server-3:11113/eureka

static:
  resource:
    mapping: /img/**=file:.//mnt/samba/realImg/
