package com.dlfc.services.feedback.entity;


import lombok.Getter;
import lombok.Setter;

import java.util.Date;


@Getter
@Setter
public class UsrFeedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_feedback.ID
     *
     * @mbggenerated Tue May 30 08:47:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_feedback.PINDEX
     *
     * @mbggenerated Tue May 30 08:47:20 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_feedback.UID
     *
     * @mbggenerated Tue May 30 08:47:20 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_feedback.PHONE
     *
     * @mbggenerated Tue May 30 08:47:20 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_feedback.MAIL
     *
     * @mbggenerated Tue May 30 08:47:20 CST 2017
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_feedback.CONTENT
     *
     * @mbggenerated Tue May 30 08:47:20 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_feedback.SUBMIT_TIME
     *
     * @mbggenerated Tue May 30 08:47:20 CST 2017
     */
    private Date submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_feedback.RESOURCE
     *
     * @mbggenerated Tue May 30 08:47:20 CST 2017
     */
    private String resource;

}