package com.dlfc.zfgj.entity;

import com.dlfc.zfgj.common.data.DataEntity;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;



@Getter
@Setter
public class ConHouseUserChildren extends DataEntity<ConHouseUserChildren> implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.ID
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.PINDEX
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.CID
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.NAME
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.GENDER
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.BIRTHDAY
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.ID_NO
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.CREATE_USER
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.CREATE_USER_IDENTITY
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.CREATE_TIME
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.MODIFY_USER
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.MODIFY_TIME
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.DELETE_FLG
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column con_house_user_children.VERSION
     *
     * @mbggenerated Thu Jun 08 10:15:42 CST 2017
     */
    private Integer version;

}