server:
  port: 28092

spring:
  application:
    name: dlfc-zfw-collect-services

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:11112/eureka,http://eureka-server-3:11113/eureka