server:
  port: 28190

spring:
  application:
    name: dlfc-zfw-regisrty-services

eureka:
  client:
    service-url:
      defaultZone: http://10.32.156.155:11114/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000