server:
  port: 28190

spring:
  application:
    name: dlfc-zfw-regisrty-services

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-2:11112/eureka,http://eureka-server-3:11113/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000