package com.dlfc.services.unicom.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;


@Getter
@Setter
public class SysCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.ID
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.TYPE
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.TYPE_NAME
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.CODE
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.NAME
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.DCRP
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private String dcrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.SORT
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.CREATE_USER
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.CREATE_USER_IDENTITY
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.CREATE_TIME
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.MODIFY_USER
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.MODIFY_TIME
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.DELETE_FLG
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code.VERSION
     *
     * @mbggenerated Mon May 29 15:55:08 CST 2017
     */
    private Integer version;
}