package com.dlfc.services.house.entity;

import lombok.Getter;
import lombok.Setter;


@Getter
@Setter
public class AgtEmpInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.ID
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.PINDEX
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.AVATAR_ID
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String avatarId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.COMPANY_ID
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.OFFICE_ID
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String officeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.ROLE_CODE
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.PHONE
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.PID
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.USER_ID
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.STATUS
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.STATUS_TIME
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String statusTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.COMMENT
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.CREATE_USER
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.CREATE_USER_IDENTITY
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.CREATE_TIME
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.MODIFY_USER
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.MODIFY_TIME
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.DELETE_FLG
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.VERSION
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.GRADE
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agt_emp_info.SORT
     *
     * @mbggenerated Tue May 30 09:24:33 CST 2017
     */
    private String sort;
}