package com.dlfc.services.house.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class SysDescriptions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.ID
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.LID
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.DESCRIPTION_1
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String description1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.DCRP_TXT_1
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String dcrpTxt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.DESCRIPTION_2
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String description2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.DCRP_TXT_2
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String dcrpTxt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.DESCRIPTION_3
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String description3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.DCRP_TXT_3
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String dcrpTxt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.CREATE_USER
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.CREATE_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.CREATE_TIME
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.MODIFY_TIME
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.CREATE_USER_copy1
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private String createUserCopy1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_descriptions.DELETE_FLG
     *
     * @mbggenerated Fri Jun 09 17:41:10 CST 2017
     */
    private Short deleteFlg;
}