package com.dlfc.services.house.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class SysHouEquipsContrast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.ID
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.CODE
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.NAME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.DCRP
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String dcrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.SORT
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.CREATE_USER
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.CREATE_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.CREATE_TIME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.MODIFY_USER
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.MODIFY_TIME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips_contrast.DELETE_FLG
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short deleteFlg;
}