package com.dlfc.services.house.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class SysHouEquips {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.ID
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.LID
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.EQUIPMENT_CODE
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String equipmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.EQUIPMENT_NAME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String equipmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.CREATE_USER
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.CREATE_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.CREATE_TIME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.MODIFY_TIME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.CREATE_USER_copy1
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String createUserCopy1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hou_equips.DELETE_FLG
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short deleteFlg;
}