package com.dlfc.services.house.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class SysSurFacis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.ID
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.LID
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.FACILITY_CODE
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String facilityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.FACILITY_NAME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String facilityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.OTHERS
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String others;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.CREATE_USER
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.CREATE_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.CREATE_TIME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.MODIFY_TIME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.CREATE_USER_copy1
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String createUserCopy1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sur_facis.DELETE_FLG
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short deleteFlg;
}