package com.dlfc.services.house.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class SysTrafficLines {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.ID
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.LID
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.TRAFFIC_LINE
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String trafficLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.OTHERS
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String others;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.CREATE_USER
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.CREATE_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.CREATE_TIME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.MODIFY_TIME
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.CREATE_USER_copy1
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private String createUserCopy1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_traffic_lines.DELETE_FLG
     *
     * @mbggenerated Fri Jun 09 17:33:26 CST 2017
     */
    private Short deleteFlg;
}