package com.dlfc.services.search.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class Person {

    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.PINDEX
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.NAME
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.ID_TYPE
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Integer idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.ID_NO
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.POSTAL_CODE
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.ADDRESS
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.CONTACT_WAY
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String contactWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.STATUS
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.REJECT_TYPE
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Integer rejectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.REJECT_REASON
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String rejectReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.QQ
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.MSN
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String msn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.ORIGIN
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.MARRIAGE
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.DEGREE
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.WORK_EXP
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short workExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.INDUSTRY
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.SALARY
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.CERT_TIME
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String certTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.CERT_STATUS
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short certStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.CREATE_USER
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.CREATE_USER_IDENTITY
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.CREATE_TIME
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.MODIFY_USER
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.MODIFY_TIME
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.DELETE_FLG
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.VERSION
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.TO_SPECIAL
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private Integer toSpecial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.LOCK_USERID
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String lockUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_person.LOCK_TIME
     *
     * @mbggenerated Mon May 29 16:01:34 CST 2017
     */
    private String lockTime;
}
