package com.dlfc.services.message.entity;


import lombok.Getter;
import lombok.Setter;

import java.util.Date;


@Getter
@Setter
public class SysMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.ID
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.PINDEX
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.RECEIVER_UID
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String receiverUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.RECEIVER_NAME
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.TITLE
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.CONTENT
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.URL
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.STATUS
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.LINKID
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String linkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.SYSID
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String sysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.TYPE
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.MASS_FLG
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Short massFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.SENDER_UID
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String senderUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.SENDER_NAME
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String senderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.SEND_TIME
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.CREATE_USER
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.CREATE_USER_IDENTITY
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.CREATE_TIME
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.MODIFY_USER
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.MODIFY_TIME
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.DELETE_FLG
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.VERSION
     *
     * @mbggenerated Wed May 31 11:21:28 CST 2017
     */
    private Integer version;
}