package com.dlfc.services.order.entity;


import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;

@Getter
@Setter
public class SysBroadband {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.ID
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.NO
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.PINDEX
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.NAME
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.PRICE
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.CYCLE
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.TYPE
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.IMG1
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String img1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.IMG2
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String img2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.IMG3
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String img3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.CONTACT_NAME
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.PHONE
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.REF_PHONE
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String refPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.ADD1
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String add1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.ADD2
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String add2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.TIME_TYPE
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String timeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.SALE
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private BigDecimal sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.EPRICE
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private BigDecimal eprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.STATUS
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.speed
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.COMMENT
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.CREATE_USER
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.CREATE_USER_IDENTITY
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.CREATE_TIME
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.MODIFY_USER
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.MODIFY_TIME
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.DELETE_FLG
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_broadband.VERSION
     *
     * @mbggenerated Mon Jun 05 15:05:51 CST 2017
     */
    private Integer version;
}