package com.dlfc.services.order.entity;


import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;


@Getter
@Setter
public class SysOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.ID
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PINDEX
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.ORDER_NO
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.U_ID
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.LID
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PRD_NAME
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String prdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.MERCHANT_ID
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.TRADING_NO
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String tradingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.SYS_NO
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String sysNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.STATUS
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.RECORD_CNT
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private Integer recordCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.LOGIC_FROM
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String logicFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.LOGIC_TO
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String logicTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PAY_TYPE
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PAYMENT_NAME
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String paymentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PAYMENT_TEL
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String paymentTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PAYMENT_IDNO
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String paymentIdno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PAYMENT_CARDNO
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String paymentCardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PAYMENT_BANKCODE
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String paymentBankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.TOTAL_AMOUNT
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.IO_FLAG
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String ioFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.PAYMENT_CHANNELS
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String paymentChannels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.CREATE_USER
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.CLIENTIP
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String clientip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.REMARK1
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.REMARK2
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.TXCODE
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String txcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.INSTALLNUM
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private Integer installnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.IS_REFUND
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String isRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.CREATE_USER_IDENTITY
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private Short createUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.CREATE_TIME
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.MODIFY_USER
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.MODIFY_USER_IDENTITY
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private Short modifyUserIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.MODIFY_TIME
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.DELETE_FLG
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private Short deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_order.VERSION
     *
     * @mbggenerated Sat Jun 03 13:24:30 CST 2017
     */
    private Integer version;
}