server:
  port: 28093

spring:
  application:
    name: dlfc-zfw-auth-services

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 20
  client:
    service-url:
      defaultZone: http://eureka-server-2:11112/eureka,http://eureka-server-3:11113/eureka

feign:
  hystrix:
    enabled: false

dlfc:
  user:
    ip: http://10.32.159.212
    port: 8083
    path: /dlfc-zhzx/api/userinfo/realNameAuth